version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/practice_mgmt
      - JWT_SECRET=your_jwt_secret_here
      - STRIPE_SECRET_KEY=your_stripe_secret_key_here
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/google-credentials.json
    depends_on:
      - mongo
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    stdin_open: true
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: